/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.Conexion;
import Entidades.Alumno;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MeD Servicios Inf
 */
public class Alumnos extends javax.swing.JFrame {
	private Connection con = null;
	private LocalDate fechaNacimiento; 
	private Alumno alumno; 
	
 private DefaultTableModel modelo = new DefaultTableModel();
	public Alumnos() {
		initComponents();
		con=Conexion.getConexion(); 
		setLocationRelativeTo(null);	
		alumnoData = new AlumnoData();
		
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jDesktopPane1 = new javax.swing.JDesktopPane();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtDni = new javax.swing.JTextField();
                txtApellido = new javax.swing.JTextField();
                txtNombre = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                radioCursando = new javax.swing.JRadioButton();
                dateFechaNacimiento = new com.toedter.calendar.JDateChooser();
                btnNuevoAlumno = new javax.swing.JButton();
                btnGuardarAlumno = new javax.swing.JButton();
                btnEliminarAlumno = new javax.swing.JButton();
                btnSalirAlumno = new javax.swing.JButton();
                btnBuscarAlumno = new javax.swing.JButton();
                btnModificar = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                labIdAlumno = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumnos.png"))); // NOI18N
                jLabel1.setText("Alumnos");

                jLabel2.setText("DNI");

                jLabel3.setText("Apellido");

                jLabel4.setText("Nombre");

                jLabel5.setText("Estado");

                jLabel6.setText("Fecha Nac");

                radioCursando.setText("Cursando");

                btnNuevoAlumno.setText("Limpiar Campos");
                btnNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNuevoAlumnoActionPerformed(evt);
                        }
                });

                btnGuardarAlumno.setText("Guardar");
                btnGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGuardarAlumnoActionPerformed(evt);
                        }
                });

                btnEliminarAlumno.setText("Eliminar");
                btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarAlumnoActionPerformed(evt);
                        }
                });

                btnSalirAlumno.setText("Salir");
                btnSalirAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSalirAlumnoActionPerformed(evt);
                        }
                });

                btnBuscarAlumno.setText("Buscar");
                btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarAlumnoActionPerformed(evt);
                        }
                });

                btnModificar.setText("Modificar");
                btnModificar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarActionPerformed(evt);
                        }
                });

                jLabel7.setText("ID Alumno");

                labIdAlumno.setText("----");

                jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(txtDni, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(txtApellido, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(radioCursando, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(dateFechaNacimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnNuevoAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnGuardarAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnEliminarAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnSalirAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnBuscarAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(btnModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
                jDesktopPane1.setLayer(labIdAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);

                javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
                jDesktopPane1.setLayout(jDesktopPane1Layout);
                jDesktopPane1Layout.setHorizontalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                .addComponent(btnGuardarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel7))
                                                                .addGap(39, 39, 39)
                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtNombre)
                                                                        .addComponent(txtApellido)
                                                                        .addComponent(radioCursando)
                                                                        .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                                                                .addGap(9, 9, 9)
                                                                                .addComponent(labIdAlumno)
                                                                                .addGap(131, 131, 131)
                                                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(btnNuevoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(btnSalirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                                .addGap(16, 16, 16)))
                                .addContainerGap(16, Short.MAX_VALUE))
                );
                jDesktopPane1Layout.setVerticalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscarAlumno))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(radioCursando))
                                .addGap(31, 31, 31)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(dateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(labIdAlumno)
                                        .addComponent(btnNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(btnSalirAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnGuardarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jDesktopPane1)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDesktopPane1)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
               int dni = Integer.parseInt(txtDni.getText());        
        alumno = alumnoData.buscarAlumnoPorDni(dni);
        
        if (alumno != null) {
            txtDni.setText(String.valueOf(alumno.getDni()));
            txtApellido.setText(alumno.getApellido());
            txtNombre.setText(alumno.getNombre());
            java.util.Date fechaNacimientoUtil = java.sql.Date.valueOf(alumno.getFechaNacimiento());
            dateFechaNacimiento.setDate(fechaNacimientoUtil);
            radioCursando.setSelected(alumno.isActivo());
	    labIdAlumno.setText(String.valueOf(alumno.getIdAlumno()));
        } else {
            JOptionPane.showMessageDialog(this, "Por favor verifique el DNI e intente nuevamente.");
        }
        }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

        private void btnNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoActionPerformed
		limpiarCampos();
		 
        }//GEN-LAST:event_btnNuevoAlumnoActionPerformed

        private void btnGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnoActionPerformed
                // TODO add your handling code here:
		int dni=Integer.parseInt(txtDni.getText());
		String apellido=txtApellido.getText();
		String nombre=txtNombre.getText();
		
		SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
		String fecha = formatoFecha.format(dateFechaNacimiento.getDate());
		LocalDate fechaNacimiento = LocalDate.parse(fecha, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
		
		boolean estado = radioCursando.isEnabled();
		
		Alumno alumno = new  Alumno(dni, apellido, nombre, fechaNacimiento, estado);
		alumnoData.guardarAlumno(alumno);
		limpiarCampos();
		
        }//GEN-LAST:event_btnGuardarAlumnoActionPerformed

        private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
                // TODO add your handling code here:
		if (alumno != null) {
		 int dni = Integer.parseInt(txtDni.getText());
		String apellido = txtApellido.getText();
		String nombre = txtNombre.getText();
    
    // obtener la fecha de nacimiento
    
		java.sql.Date fechaNacimientoSQL = new java.sql.Date(dateFechaNacimiento.getDate().getTime());
		fechaNacimiento = fechaNacimientoSQL.toLocalDate(); 

    // Obtener el estado del alumno
		boolean estado = radioCursando.isEnabled();

    // Obtener el objeto Alumno a modificar y obtener su ID
		Alumno alumnoModificado = new Alumno(dni, apellido, nombre, fechaNacimiento, estado);
		alumnoModificado.setIdAlumno(alumno.getIdAlumno());  // Aquí se obtiene el ID del alumno a modificar desde el objeto alumno
    
    // Llamar al método modificarAlumno de AlumnoData para aplicar la modificación
    AlumnoData alumnoData = new AlumnoData();
    alumnoData.modificarAlumno(alumnoModificado);
    limpiarCampos();
    } else {
            JOptionPane.showMessageDialog(this, "No se ha buscado ningún alumno para modificar.");
        }
        }//GEN-LAST:event_btnModificarActionPerformed

        private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
                 int idAlumno = obtenerIdAlumno();  // Suponiendo que tienes un método para obtener el ID del alumno
    
    if (idAlumno != -1) {
        // Llama al método en AlumnoData para eliminar al alumno
        alumnoData.eliminarAlumno(idAlumno);
        
        // Si se eliminó exitosamente, limpia los campos
        limpiarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo obtener el ID del alumno para eliminar.");
    }
        }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

        private void btnSalirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAlumnoActionPerformed
              this.dispose();
        }//GEN-LAST:event_btnSalirAlumnoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Alumnos().setVisible(true);
			}
		});
	}
	AlumnoData alumnoData = new AlumnoData();
	


// Método para convertir una fecha en formato String a un objeto Date

	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton btnBuscarAlumno;
        public javax.swing.JButton btnEliminarAlumno;
        public javax.swing.JButton btnGuardarAlumno;
        public javax.swing.JButton btnModificar;
        public javax.swing.JButton btnNuevoAlumno;
        public javax.swing.JButton btnSalirAlumno;
        public com.toedter.calendar.JDateChooser dateFechaNacimiento;
        private javax.swing.JDesktopPane jDesktopPane1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        public javax.swing.JLabel labIdAlumno;
        public javax.swing.JRadioButton radioCursando;
        public javax.swing.JTextField txtApellido;
        public javax.swing.JTextField txtDni;
        public javax.swing.JTextField txtNombre;
        // End of variables declaration//GEN-END:variables

private void limpiarCampos() {
    txtDni.setText("");
    txtApellido.setText("");
    txtNombre.setText("");
    dateFechaNacimiento.setDate(null);  // Para limpiar el JDateChooser
    radioCursando.setSelected(false);
    labIdAlumno.setText("---");
}

private int obtenerIdAlumno() {
    try {
        // Supongamos que puedes obtener el ID del alumno de algún componente en tu interfaz gráfica
        return Integer.parseInt(labIdAlumno.getText());
    } catch (NumberFormatException e) {
        return -1;  // Retorna -1 si no se puede convertir a entero (por ejemplo, si no es un número válido)
    }
}



}
